### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by tadast** [TomasAchmedovas/paysera#4]
First of all, thanks for the gem, it saved me a bunch of time :)

Praise aside, I'm getting to failures when running the project test suite:

```
Failures:

  1) Paysera::Response#bank? when sms response should equal false
     Failure/Error: it { expect(sms_response.bank?).to be false }

       expected false
            got true
     # ./spec/response_spec.rb:71:in `block (4 levels) in <top (required)>'

  2) Paysera::Response#sms? when bank response should equal true
     Failure/Error: it { expect(sms_response.sms?).to be true }

       expected true
            got false
     # ./spec/response_spec.rb:85:in `block (4 levels) in <top (required)>'

Finished in 1.81 seconds (files took 0.13569 seconds to load)
21 examples, 2 failures

Failed examples:

rspec ./spec/response_spec.rb:71 # Paysera::Response#bank? when sms response should equal false
rspec ./spec/response_spec.rb:85 # Paysera::Response#sms? when bank response should equal true
```

I didn't have much time to investigate, so just wanted to raise your attention to that. If you have any pointers of why this may be happening, let me know.

**Comment by minvs1** [comment]
Thanks to you for contribution :)

Thing is Paysera didn't activate my project so I couldn't test SMS response properly. I will fix this as soon as possible.

**Comment by tadast** [comment]
This feature is working properly with production responses. 

Also, could you please release a new version with my PR's you just merged?

**Comment by minvs1** [comment]
Done.

**Comment by tadast** [comment]
Thanks!
